# Add application configuration variables here, as shown below.
#
# AWS Login Consts
AWS_ACCESS_KEY_ID:      ""
AWS_SECRET_ACCESS_KEY:  ""

development:
    SENDGRID_USERNAME:  ""
    SENDGRID_PASSWORD:  ""
    AWS_BUCKET:         
production:
AWS_BUCKET:         
